# Generated by Django 5.1.3 on 2026-06-18 14:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("venues", "0006_alter_pitchschedule_pitch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_trackin_6081b7_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_booking_90270f_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_status_d621e5_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_transac_a1f824_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_payment_f51455_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_booking_52233d_idx",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="confirmed_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="callback_data",
        ),
        migrations.AddField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 6, 18, 14, 14, 17, 59259, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["expires_at"], name="bookings_expires_f10cd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="unique_pending_booking_per_user",
            ),
        ),
    ]
