apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: sport-booking

type: Opaque


stringData:
  SECRET_KEY: "django-insecure-)velb@wjrt#+f#qd1ahss1q%^g9c4a)-i0x)%5hh&#0ez+h5wj"
