# Generated by Django 5.1.3 on 2026-06-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_created", "Booking Created"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("payment_success", "Payment Successful"),
                    ("system_alert", "System Alert"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
