# Generated by Django 5.1.3 on 2026-05-26 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.apps.venues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=11, unique=True)),
                ("facilities", models.TextField(blank=True)),
                ("rules", models.TextField(blank=True)),
                ("cancellation_policy", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_venues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="manager of venue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pitch_name", models.CharField(max_length=100)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("1", "football"),
                            ("2", "futsal"),
                            ("3", "volleyball"),
                            ("4", "tennis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "surface_type",
                    models.CharField(
                        choices=[
                            ("grass", "Grass"),
                            ("artificial", "Artificial"),
                            ("parquet", "Parquet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                (
                    "weekend_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="if not set, same as price_per_hour",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("has_lighting", models.BooleanField(db_index=True, default=True)),
                ("has_changing_room", models.BooleanField(db_index=True, default=True)),
                ("has_parking", models.BooleanField(db_index=True, default=False)),
                ("has_cafeteria", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="venues.venue",
                        verbose_name="saloon",
                    ),
                ),
            ],
            options={
                "db_table": "pitches",
                "ordering": ["venue", "pitch_name"],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "saturday"),
                            (2, "sunday"),
                            (3, "monday"),
                            (4, "tuesday"),
                            (5, "wednesday"),
                            (6, "thursday"),
                            (7, "friday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="pitch_start_time")),
                ("end_time", models.TimeField(verbose_name="pitch_end_time")),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "pitch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="venues.pitch",
                    ),
                ),
            ],
            options={
                "db_table": "working_hours",
                "ordering": ["pitch", "day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="maximum 5 megabyte",
                        upload_to=backend.apps.venues.models.pitch_image_path,
                        validators=[backend.apps.venues.models.validate_image_size],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pitch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="venues.pitch",
                    ),
                ),
            ],
            options={
                "db_table": "pitch_images",
                "ordering": ["uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["pitch"], name="pitch_image_pitch_i_63b2d1_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="venues_venu_is_acti_3f4912_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["is_active"], name="venues_venu_is_acti_954204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["venue_name"], name="venues_venu_venue_n_486ee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(fields=["slug"], name="venues_venu_slug_f5c9e1_idx"),
        ),
        migrations.AddIndex(
            model_name="venue",
            index=models.Index(
                fields=["-created_at"], name="venues_venu_created_e94816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(
                fields=["venue", "is_active"], name="pitches_venue_i_fb8d5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(
                fields=["sport_type"], name="pitches_sport_t_dac4b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(fields=["is_active"], name="pitches_is_acti_8d1fb0_idx"),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(
                fields=["price_per_hour"], name="pitches_price_p_7395d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(fields=["capacity"], name="pitches_capacit_9a5dd0_idx"),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(fields=["slug"], name="pitches_slug_0fd3c4_idx"),
        ),
        migrations.AddIndex(
            model_name="pitch",
            index=models.Index(
                fields=["-created_at"], name="pitches_created_5ce3eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workinghours",
            index=models.Index(
                fields=["pitch", "day_of_week"], name="working_hou_pitch_i_75af6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workinghours",
            index=models.Index(
                fields=["pitch", "is_closed"], name="working_hou_pitch_i_07d514_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together={("pitch", "day_of_week")},
        ),
    ]
