# Generated by Django 5.1.3 on 2026-06-06 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pitch",
            name="pitches_slug_0fd3c4_idx",
        ),
        migrations.RemoveField(
            model_name="pitch",
            name="slug",
        ),
        migrations.AlterField(
            model_name="venue",
            name="manager",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_venue",
                to=settings.AUTH_USER_MODEL,
                verbose_name="manager of venue",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="pitch_end_time"
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="pitch_start_time"
            ),
        ),
    ]
