# Generated by Django 5.1.3 on 2026-06-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_remove_pitch_pitches_slug_0fd3c4_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PitchSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "saturday"),
                            (2, "sunday"),
                            (3, "monday"),
                            (4, "tuesday"),
                            (5, "wednesday"),
                            (6, "thursday"),
                            (7, "friday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="workinghours",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workinghours",
            name="pitch",
        ),
        migrations.RemoveIndex(
            model_name="venue",
            name="venues_venu_slug_f5c9e1_idx",
        ),
        migrations.AddField(
            model_name="pitchschedule",
            name="pitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="venues.pitch",
            ),
        ),
        migrations.DeleteModel(
            name="WorkingHours",
        ),
    ]
