# Generated by Django 5.1.3 on 2026-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_pitchschedule_alter_workinghours_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitch",
            name="sport_type",
            field=models.CharField(
                choices=[
                    ("football", "football"),
                    ("futsal", "futsal"),
                    ("volleyball", "volleyball"),
                    ("tennis", "tennis"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pitchschedule",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("saturday", "saturday"),
                    ("sunday", "sunday"),
                    ("monday", "monday"),
                    ("tuesday", "tuesday"),
                    ("wednesday", "wednesday"),
                    ("thursday", "thursday"),
                    ("friday", "friday"),
                ],
                db_index=True,
            ),
        ),
    ]
