# Generated by Django 5.1.3 on 2026-06-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_alter_pitch_sport_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitchschedule",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("saturday", "saturday"),
                    ("sunday", "sunday"),
                    ("monday", "monday"),
                    ("tuesday", "tuesday"),
                    ("wednesday", "wednesday"),
                    ("thursday", "thursday"),
                    ("friday", "friday"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
