# Generated by Django 5.1.3 on 2026-06-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0005_alter_pitchschedule_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitchschedule",
            name="pitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="venues.pitch",
            ),
        ),
    ]
