# Generated by Django 5.1.3 on 2026-05-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_useraccount_accepted_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_complex_manager",
            field=models.BooleanField(default=False),
        ),
    ]
